/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
 */
        CKEDITOR.plugins.setLang("a11yhelp", "lv", {title:"Pieejamības instrukcija", contents:"Palīdzības saturs. Lai aizvērtu ciet šo dialogu nospiediet ESC.", legend:[{name:"Galvenais", items:[{name:"Redaktora rīkjosla", legend:"Nospiediet ${toolbarFocus} lai p�?rvietotos uz rīkjoslu. Lai p�?rvietotos uz n�?košo vai iepriekšējo rīkjoslas grupu izmantojiet pogu TAB un SHIFT+TAB.  Lai p�?rvietotos uz n�?košo vai iepriekšējo rīkjoslas pogu izmantojiet Kreiso vai Labo bultiņu. Nospiediet Atstarpi vai ENTER lai aktivizētu rīkjosla pogu."},
                {name:"Redaktora dialoga  logs", legend:"Dialoga log�? nospiediet pogu TAB lai p�?rvietotos uz n�?košo dialoga loga lauku, nospiediet SHIFT+TAB lai atgrieztos iepriekšēj�? lauk�?, nospiediet ENTER lai apstiprin�?tu dialoga datus, nospiediet ESC lai aizvērtu šo dialogu. Dialogam kuram ir vair�?kas cilnes, nospiediet ALT+F10 lai p�?rvietotos uz nepieciešamo cilni.  Lai p�?rvietotos uz n�?košo cilni izmantojiet pogu TAB vai Labo bultiņu. Lai p�?rvietotos uz iepriekšējo cilni nospiediet SHIFT+TAB vai kreiso bultiņu. Nospiediet SPACE vai ENTER lai izvēlētos lapas cilni."},
                {name:"Redaktora satura izvēle", legend:"Nospiediet ${contextMenu} vai APPLICATION KEY lai atvērtu satura izvēlni. Lai p�?rvietotos uz n�?košo izvēlnes opciju izmantojiet pogu TAB vai pogu Bultiņu uz leju. Lai p�?rvietotos uz iepriekšējo opciju izmantojiet  SHIFT+TAB vai pogu Bultiņa uz augšu. Nospiediet SPACE vai ENTER lai izvelētos izvēlnes opciju. Atveriet tekošaj�? opcija apakšizvēlni ar SAPCE vai ENTER ka ari to var izdarīt ar Labo bultiņu. Lai atgrieztos atpakaļ uz sakuma izvēlni nospiediet ESC vai Kreiso bultiņu. Lai aizvērtu ciet izvēlnes saturu nospiediet ESC."},
                {name:"Redaktora saraksta lauks", legend:"Saraksta lauk�?, lai p�?rvietotos uz n�?košo saraksta elementu nospiediet TAB vai pogu Bultiņa uz leju. Lai p�?rvietotos uz iepriekšējo saraksta elementu nospiediet SHIFT+TAB vai pogu Bultiņa uz augšu. Nospiediet SPACE vai ENTER lai izvēlētos saraksta opcijas. Nospiediet ESC lai aizvērtu saraksta lauku. "}, {name:"Redaktora elementa ceļa josla", legend:"Nospiediet ${elementsPathFocus} lai p�?rvietotos uz  elementa ceļa joslu. Lai p�?rvietotos uz n�?košo elementa pogu izmantojiet TAB vai Labo bultiņu. Lai p�?rvietotos uz iepriekšējo elementa pogu  izmantojiet SHIFT + TAB vai Kreiso bultiņu. Nospiediet SPACE vai ENTER lai izvēlētos elementu redaktor�?."}]},
                {name:"Komandas", items:[{name:"Komanda atcelt darbību", legend:"Nospiediet ${undo}"}, {name:"Komanda atk�?rtot darbību", legend:"Nospiediet ${redo}"}, {name:"Treknraksta komanda", legend:"Nospiediet ${bold}"}, {name:"Kursīva komanda", legend:"Nospiediet ${italic}"}, {name:"Apakšsvītras komanda ", legend:"Nospiediet ${underline}"}, {name:"Hipersaites komanda", legend:"Nospiediet ${link}"}, {name:"Rīkjoslas aizvēršanas komanda", legend:"Nospiediet ${toolbarCollapse}"}, {name:"Piekļūt iepriekšējai fokusa vietas komandai",
                        legend:"Nospiediet ${accessPreviousSpace} lai piekļūtu tuv�?kajai nepieejamajai fokusa vietai pirms kursora. Piemēram: diviem blakus esošiem līnijas HR elementiem. Atk�?rtojiet taustiņu kombin�?ciju lai piekļūtu pie t�?l�?k�?m viet�?m."}, {name:"Piekļūt n�?koš�? fokusa apgabala komandai", legend:"Nospiediet ${accessNextSpace} lai piekļūtu tuv�?kajai nepieejamajai fokusa vietai pēc kursora. Piemēram: diviem blakus esošiem līnijas HR elementiem. Atk�?rtojiet taustiņu kombin�?ciju lai piekļūtu pie t�?l�?k�?m viet�?m."},
                        {name:"Pieejamības palīdzība", legend:"Nospiediet ${a11yHelp}"}]}]});